"""Unit tests for the shared install detect_invocation helper."""

from __future__ import annotations

import struct
import sys
from pathlib import Path

import pytest

_IMAGE_SUBSYSTEM_WINDOWS_GUI = 2
_IMAGE_SUBSYSTEM_WINDOWS_CUI = 3  # console


def _write_fake_pe(path: Path, subsystem: int) -> None:
    """Write a minimal PE image carrying the given Subsystem field.

    Just enough structure for ``_common._is_gui_subsystem`` to parse: an MZ
    stub whose ``e_lfanew`` points at a ``PE\\0\\0`` signature, a zeroed COFF
    header, and an optional header long enough to hold the Subsystem field
    at offset 68. Used to stand in for a genuine GUI-subsystem ``pythonw.exe``
    (CPython) versus the console-subsystem copy uv ships in its venvs.
    """
    pe_offset = 0x80
    buf = bytearray(pe_offset + 4 + 20 + 70)
    buf[0:2] = b"MZ"
    struct.pack_into("<I", buf, 0x3C, pe_offset)
    buf[pe_offset : pe_offset + 4] = b"PE\x00\x00"
    struct.pack_into("<H", buf, pe_offset + 4 + 20 + 68, subsystem)
    path.write_bytes(bytes(buf))


def test_detect_invocation_frozen_returns_executable_with_daemon(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Frozen non-Windows: return sys.executable + "daemon".

    Windows has its own test (test_detect_invocation_windows_frozen_*) that
    asserts the dbxignorew.exe sibling lookup.
    """
    if sys.platform == "win32":
        pytest.skip("Windows frozen path tested separately via dbxignorew sibling tests")
    cli_exe = tmp_path / "dbxignore"
    cli_exe.write_text("")
    monkeypatch.setattr(sys, "frozen", True, raising=False)
    monkeypatch.setattr(sys, "executable", str(cli_exe))
    from dbxignore.install import _common

    exe, args = _common.detect_invocation()
    assert exe == cli_exe
    assert args == "daemon"


def test_detect_invocation_falls_back_to_python_module(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delattr(sys, "frozen", raising=False)
    # Force the Linux/macOS branch — the Windows branch has its own
    # launcher precedence (dbxignorew / pythonw / python) covered separately.
    monkeypatch.setattr(sys, "platform", "linux")
    monkeypatch.setattr(sys, "executable", "/usr/bin/python3")
    monkeypatch.setattr("shutil.which", lambda _name: None)
    from dbxignore.install import _common

    exe, args = _common.detect_invocation()
    assert exe == Path("/usr/bin/python3")
    assert args == "-m dbxignore daemon"


def test_detect_invocation_uses_path_shim_when_present(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "linux")

    def fake_which(name: str) -> str | None:
        if name == "dbxignore":
            return "/home/u/.local/bin/dbxignore"
        return None

    monkeypatch.setattr("shutil.which", fake_which)
    from dbxignore.install import _common

    exe, args = _common.detect_invocation()
    assert exe == Path("/home/u/.local/bin/dbxignore")
    assert args == "daemon"


def test_detect_invocation_windows_prefers_dbxignorew_sibling(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Windows non-frozen, ``dbxignorew.exe`` sibling present: select it.

    The ``dbxignorew`` GUI-script trampoline (declared in pyproject.toml
    ``[project.gui-scripts]``) is generated by pip/uv as a real
    GUI-subsystem launcher next to ``sys.executable``. It is the non-frozen
    analogue of the frozen ``dbxignorew.exe`` and runs the daemon windowless,
    so it is preferred over ``pythonw.exe``.

    Uses ``tmp_path`` for the executable rather than a hardcoded
    ``C:\\…\\python.exe`` literal: on POSIX hosts ``Path(r"C:\\…")`` parses
    the whole backslash string as a single filename (no path components),
    so ``Path.with_name(...)`` collapses to a bare filename and the
    assertion fails on the cross-platform CI legs.
    """
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    monkeypatch.setattr("shutil.which", lambda _name: None)
    python_exe = tmp_path / "Scripts" / "python.exe"
    python_exe.parent.mkdir()
    python_exe.write_text("")
    # pythonw.exe also present — the sibling still wins.
    _write_fake_pe(tmp_path / "Scripts" / "pythonw.exe", _IMAGE_SUBSYSTEM_WINDOWS_GUI)
    dbxignorew_exe = tmp_path / "Scripts" / "dbxignorew.exe"
    dbxignorew_exe.write_text("")
    monkeypatch.setattr(sys, "executable", str(python_exe))
    from dbxignore.install import _common

    exe, args = _common.detect_invocation()
    assert exe == dbxignorew_exe
    assert args == "daemon"


def test_detect_invocation_windows_rejects_dbxignorew_sibling_with_console_pythonw(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Windows non-frozen, ``dbxignorew.exe`` sibling present but its companion
    ``pythonw.exe`` is console-subsystem: do NOT return the sibling.

    The non-frozen ``dbxignorew.exe`` is a GUI-script trampoline that re-execs
    the sibling ``pythonw.exe`` to do the actual work — it is only genuinely
    windowless when that ``pythonw.exe`` is itself GUI-subsystem. uv project
    venvs (``uv sync`` / ``uv run``) ship a console-subsystem ``pythonw.exe``,
    so their ``dbxignorew.exe`` still allocates a console window. Returning it
    would be a windowed launcher dressed up as a windowless one; fall through
    to ``python.exe`` with the honest WARNING instead.
    """
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    monkeypatch.setattr("shutil.which", lambda _name: None)
    python_exe = tmp_path / "Scripts" / "python.exe"
    python_exe.parent.mkdir()
    python_exe.write_text("")
    # dbxignorew.exe sibling exists, but its companion pythonw.exe is
    # console-subsystem — the uv project-venv layout.
    (tmp_path / "Scripts" / "dbxignorew.exe").write_text("")
    _write_fake_pe(tmp_path / "Scripts" / "pythonw.exe", _IMAGE_SUBSYSTEM_WINDOWS_CUI)
    monkeypatch.setattr(sys, "executable", str(python_exe))
    from dbxignore.install import _common

    with caplog.at_level("WARNING", logger="dbxignore.install._common"):
        exe, args = _common.detect_invocation()

    assert exe == python_exe
    assert args == "-m dbxignore daemon"
    assert any("console window" in rec.message for rec in caplog.records)


def test_detect_invocation_windows_uses_dbxignorew_on_path(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Windows non-frozen, no sibling but ``dbxignorew`` on PATH: select it.

    Covers the ``uv tool install`` layout where the GUI-script trampoline
    lands in a bin directory on PATH rather than next to ``sys.executable``.
    """
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    python_exe = tmp_path / "Scripts" / "python.exe"
    python_exe.parent.mkdir()
    python_exe.write_text("")
    monkeypatch.setattr(sys, "executable", str(python_exe))
    shim_path = str(tmp_path / "bin" / "dbxignorew.exe")

    def fake_which(name: str) -> str | None:
        return shim_path if name == "dbxignorew" else None

    monkeypatch.setattr("shutil.which", fake_which)
    from dbxignore.install import _common

    exe, args = _common.detect_invocation()
    assert exe == Path(shim_path)
    assert args == "daemon"


def test_detect_invocation_windows_prefers_local_gui_pythonw_over_path_dbxignorew(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Windows non-frozen, no sibling, but a genuine GUI-subsystem
    ``pythonw.exe`` next to ``sys.executable`` AND a ``dbxignorew`` on PATH:
    select the local ``pythonw.exe``.

    ``dbxignore install`` runs in ``sys.executable``'s environment, so the
    local ``pythonw.exe`` + ``-m dbxignore daemon`` is guaranteed tied to the
    current package. A ``dbxignorew`` on PATH could belong to a different
    dbxignore install/version, which would run the daemon in a different
    environment than the one the user just invoked. Both launchers are
    windowless; the local one wins because it cannot be the wrong package.
    """
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    python_exe = tmp_path / "Scripts" / "python.exe"
    python_exe.parent.mkdir()
    python_exe.write_text("")
    pythonw_exe = tmp_path / "Scripts" / "pythonw.exe"
    _write_fake_pe(pythonw_exe, _IMAGE_SUBSYSTEM_WINDOWS_GUI)
    monkeypatch.setattr(sys, "executable", str(python_exe))
    # A dbxignorew.exe exists on PATH — from some other install — but the
    # local GUI-subsystem pythonw.exe must still win.
    shim_path = str(tmp_path / "other-install" / "dbxignorew.exe")
    monkeypatch.setattr("shutil.which", lambda name: shim_path if name == "dbxignorew" else None)
    from dbxignore.install import _common

    exe, args = _common.detect_invocation()
    assert exe == pythonw_exe
    assert args == "-m dbxignore daemon"


def test_detect_invocation_windows_accepts_gui_subsystem_pythonw(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Windows non-frozen, no ``dbxignorew`` but a genuine GUI-subsystem
    ``pythonw.exe``: select ``pythonw.exe``.

    A real CPython / Store Python install ships a ``pythonw.exe`` whose PE
    Subsystem field is Windows GUI (2). That launches the daemon windowless,
    so it is used with ``-m dbxignore daemon``.
    """
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    monkeypatch.setattr("shutil.which", lambda _name: None)
    python_exe = tmp_path / "Scripts" / "python.exe"
    python_exe.parent.mkdir()
    python_exe.write_text("")
    pythonw_exe = tmp_path / "Scripts" / "pythonw.exe"
    _write_fake_pe(pythonw_exe, _IMAGE_SUBSYSTEM_WINDOWS_GUI)
    monkeypatch.setattr(sys, "executable", str(python_exe))
    from dbxignore.install import _common

    exe, args = _common.detect_invocation()
    assert exe == pythonw_exe
    assert args == "-m dbxignore daemon"


def test_detect_invocation_windows_rejects_console_subsystem_pythonw(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Windows non-frozen, ``pythonw.exe`` present but console-subsystem:
    reject it and fall back to ``python.exe`` with a WARNING.

    uv-created venvs ship a ``pythonw.exe`` that is a byte-identical copy of
    the console-subsystem ``python.exe`` trampoline. A Task Scheduler action
    pointing at it allocates a visible console window for the daemon's whole
    lifetime. The name promises windowless; the PE Subsystem field does not.
    detect_invocation must verify the subsystem, not trust the filename.
    """
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    monkeypatch.setattr("shutil.which", lambda _name: None)
    python_exe = tmp_path / "Scripts" / "python.exe"
    python_exe.parent.mkdir()
    python_exe.write_text("")
    # pythonw.exe present but console-subsystem — the uv venv case.
    _write_fake_pe(tmp_path / "Scripts" / "pythonw.exe", _IMAGE_SUBSYSTEM_WINDOWS_CUI)
    monkeypatch.setattr(sys, "executable", str(python_exe))
    from dbxignore.install import _common

    with caplog.at_level("WARNING", logger="dbxignore.install._common"):
        exe, args = _common.detect_invocation()

    assert exe == python_exe
    assert args == "-m dbxignore daemon"
    assert any("console window" in rec.message for rec in caplog.records)


def test_detect_invocation_windows_falls_back_when_no_gui_launcher(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Windows non-frozen, no ``dbxignorew`` and no ``pythonw.exe`` at all:
    fall back to ``python.exe`` with a WARNING.

    Item #100 — Microsoft Store Python, embedded interpreters, and pruned
    CPython installs may ship only ``python.exe``. Returning it keeps the
    daemon startable at logon; the WARNING explains the console-window
    trade-off.
    """
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    monkeypatch.setattr("shutil.which", lambda _name: None)
    python_exe = tmp_path / "Scripts" / "python.exe"
    python_exe.parent.mkdir()
    python_exe.write_text("")
    # NB: neither pythonw.exe nor dbxignorew.exe created.
    monkeypatch.setattr(sys, "executable", str(python_exe))
    from dbxignore.install import _common

    with caplog.at_level("WARNING", logger="dbxignore.install._common"):
        exe, args = _common.detect_invocation()

    assert exe == python_exe
    assert args == "-m dbxignore daemon"
    assert any("console window" in rec.message for rec in caplog.records)


def test_detect_cli_invocation_frozen_uses_sibling_exe(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Frozen PyInstaller install on non-Windows: dbxignore sibling is the registered target.

    Windows has its own test (test_detect_cli_invocation_windows_frozen_*) that
    asserts the dbxignorew.exe sibling lookup.
    """
    if sys.platform == "win32":
        pytest.skip("Windows frozen path tested separately via dbxignorew sibling tests")
    daemon_exe = tmp_path / "dbxignored"
    daemon_exe.write_text("")
    cli_exe = tmp_path / "dbxignore"
    cli_exe.write_text("")
    monkeypatch.setattr(sys, "frozen", True, raising=False)
    monkeypatch.setattr(sys, "executable", str(daemon_exe))
    from dbxignore.install import _common

    result = _common.detect_cli_invocation()
    assert result == f'"{cli_exe}"'


def test_detect_cli_invocation_uses_shutil_which_shim(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Non-frozen install: `dbxignore` PATH shim is the registered target."""
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    shim_path = "C:\\Users\\u\\.local\\bin\\dbxignore.exe"

    def fake_which(name: str) -> str | None:
        if name == "dbxignore":
            return shim_path
        return None

    monkeypatch.setattr("shutil.which", fake_which)
    from dbxignore.install import _common

    result = _common.detect_cli_invocation()
    assert result == f'"{shim_path}"'


def test_detect_cli_invocation_falls_back_to_python_module(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """No frozen install, no `dbxignore` on PATH: use `<sys.executable> -m dbxignore`."""
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    python_exe = tmp_path / "Scripts" / "python.exe"
    python_exe.parent.mkdir()
    python_exe.write_text("")
    monkeypatch.setattr(sys, "executable", str(python_exe))
    monkeypatch.setattr("shutil.which", lambda _name: None)
    from dbxignore.install import _common

    result = _common.detect_cli_invocation()
    assert result == f'"{python_exe}" -m dbxignore'


def test_detect_cli_invocation_raises_when_no_python_and_no_sys_executable(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Defensive guard: empty sys.executable + no shim must raise, not return Path('.')."""
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "win32")
    monkeypatch.setattr(sys, "executable", "")
    monkeypatch.setattr("shutil.which", lambda _name: None)
    from dbxignore.install import _common

    with pytest.raises(RuntimeError, match="dbxignore not on PATH"):
        _common.detect_cli_invocation()


def test_detect_invocation_raises_when_sys_executable_empty_and_no_python3(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """In misconfigured embedded interpreters, sys.executable may be '' or None.

    If neither it nor python3 on PATH is discoverable, detect_invocation raises
    RuntimeError rather than writing a broken executable like Path('.') into the
    systemd unit / launchd plist.
    """
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "linux")
    monkeypatch.setattr(sys, "executable", "")
    monkeypatch.setattr("shutil.which", lambda _name: None)
    from dbxignore.install import _common

    with pytest.raises(RuntimeError, match="Cannot determine Python interpreter"):
        _common.detect_invocation()


def test_detect_invocation_falls_back_to_python3_when_sys_executable_empty(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """When sys.executable is empty but python3 is on PATH, use python3 with -m dbxignore daemon."""
    monkeypatch.delattr(sys, "frozen", raising=False)
    monkeypatch.setattr(sys, "platform", "linux")
    monkeypatch.setattr(sys, "executable", "")

    def fake_which(name: str) -> str | None:
        if name == "python3":
            return "/usr/bin/python3"
        return None

    monkeypatch.setattr("shutil.which", fake_which)
    from dbxignore.install import _common

    exe, args = _common.detect_invocation()
    assert exe == Path("/usr/bin/python3")
    assert args == "-m dbxignore daemon"


@pytest.mark.skipif(sys.platform != "win32", reason="dbxignorew is Windows-only")
def test_detect_invocation_windows_frozen_returns_dbxignorew_sibling(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Windows + frozen + dbxignorew.exe sibling exists → return the sibling
    with "daemon", not sys.executable.
    """
    cli_exe = tmp_path / "dbxignore.exe"
    cli_exe.write_text("")
    helper_exe = tmp_path / "dbxignorew.exe"
    helper_exe.write_text("")
    monkeypatch.setattr(sys, "frozen", True, raising=False)
    monkeypatch.setattr(sys, "executable", str(cli_exe))
    from dbxignore.install import _common

    exe, args = _common.detect_invocation()
    assert exe == helper_exe
    assert args == "daemon"


@pytest.mark.skipif(sys.platform != "win32", reason="dbxignorew is Windows-only")
def test_detect_invocation_windows_frozen_falls_back_when_helper_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Windows + frozen + dbxignorew.exe sibling absent → fall back to
    sys.executable with a WARNING. (Defensive fallback for truncated
    bundles; ships only happen with both binaries present.)
    """
    cli_exe = tmp_path / "dbxignore.exe"
    cli_exe.write_text("")
    monkeypatch.setattr(sys, "frozen", True, raising=False)
    monkeypatch.setattr(sys, "executable", str(cli_exe))
    from dbxignore.install import _common

    with caplog.at_level("WARNING", logger="dbxignore.install._common"):
        exe, args = _common.detect_invocation()
    assert exe == cli_exe
    assert args == "daemon"
    assert "dbxignorew.exe not found" in caplog.text


@pytest.mark.skipif(sys.platform != "win32", reason="dbxignorew is Windows-only")
def test_detect_cli_invocation_windows_frozen_returns_dbxignorew_sibling(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Windows + frozen + dbxignorew.exe sibling exists → shell-verb
    registry value targets the GUI binary, so verbs invoke without a
    console flash and route output through MessageBox.
    """
    cli_exe = tmp_path / "dbxignore.exe"
    cli_exe.write_text("")
    helper_exe = tmp_path / "dbxignorew.exe"
    helper_exe.write_text("")
    monkeypatch.setattr(sys, "frozen", True, raising=False)
    monkeypatch.setattr(sys, "executable", str(cli_exe))
    from dbxignore.install import _common

    prefix = _common.detect_cli_invocation()
    assert prefix == f'"{helper_exe}"'


@pytest.mark.skipif(sys.platform != "win32", reason="dbxignorew is Windows-only")
def test_detect_cli_invocation_windows_frozen_falls_back_when_helper_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Windows + frozen + dbxignorew.exe absent → fall back to sys.executable
    with a WARNING for the shell-verb registry entry.
    """
    cli_exe = tmp_path / "dbxignore.exe"
    cli_exe.write_text("")
    monkeypatch.setattr(sys, "frozen", True, raising=False)
    monkeypatch.setattr(sys, "executable", str(cli_exe))
    from dbxignore.install import _common

    with caplog.at_level("WARNING", logger="dbxignore.install._common"):
        prefix = _common.detect_cli_invocation()
    assert prefix == f'"{cli_exe}"'
    assert "dbxignorew.exe not found" in caplog.text
