# Sourced by scripts/manual-test-{ubuntu-vps,macos}.sh.
#
# Defines shared helpers for the two bash manual-test scripts:
# - `phase_extended_cli()`: the Phase 4.5 block exercising the CLI surface
#   added across PRs #100, #102, #103, #107, #108, #195, #203, #205.
#   Extracted because the body is byte-near-identical between the two scripts
#   (~120 LOC each) and was being maintained twice; backlog item #75 is the
#   trigger.
# - `clean_uv_cache_for_dbxignore_if_local()`: Phase 2 cache-clean (item #116)
#   called from each script's `phase_dbxignore_install()` before `uv tool
#   install`. Shared because the body was an 11-line copy across both scripts.
#
# Depends on the parent script's shared environment:
#   - $DROPBOX_DIR, $TEST_SUBDIR — test-tree location
#   - $DBXIGNORE_STATE_DIR — per-user state dir (state.json, daemon.log)
#   - phase, note, pass, fail — output helpers
#   - assert_grep, assert_xattr_set, assert_xattr_unset — assertion helpers
#
# Windows (`scripts/manual-test-windows.ps1`) is PowerShell and does not
# share this body — see backlog item #75.

# Recovery hook for case 4s — called from each parent script's EXIT trap
# (cleanup()) so an abort during the destructive section restores the user's
# state.json regardless of how the script exited. The sentinels
# (`_4S_STATE_JSON`, `_4S_STATE_JSON_EXISTED`) are set inside `phase_extended_cli`
# right before the destructive operations and unset after successful
# completion; this function is a no-op when sentinels are unset.
_phase_4s_recover_state_json() {
    if [ -z "${_4S_STATE_JSON:-}" ]; then
        return 0
    fi
    chmod 644 "$_4S_STATE_JSON" 2>/dev/null || true
    if [ "${_4S_STATE_JSON_EXISTED:-0}" = "1" ] && [ -f /tmp/dbx-4s-state-backup.json ]; then
        mv -f /tmp/dbx-4s-state-backup.json "$_4S_STATE_JSON" 2>/dev/null || true
    elif [ "${_4S_STATE_JSON_EXISTED:-0}" = "0" ]; then
        rm -f "$_4S_STATE_JSON" 2>/dev/null || true
    fi
    unset _4S_STATE_JSON _4S_STATE_JSON_EXISTED
}

# BACKLOG #116: invalidate uv's path-keyed sdist cache for local-source
# installs. Without this, `uv tool install .` from a directory that's
# been built before reuses the cached wheel at `sdists-v9/path/<dir-hash>/`
# — the cache key is the source dir path, not the git SHA, so commits
# don't invalidate it. Excludes PyPI names and git URLs (which aren't
# existing directories).
clean_uv_cache_for_dbxignore_if_local() {
    if [[ -d "$DBXIGNORE_INSTALL_SPEC" ]]; then
        note "local-source DBXIGNORE_INSTALL_SPEC — cleaning uv cache for dbxignore (item #116)"
        uv cache clean dbxignore >/dev/null 2>&1 || true
    fi
}


phase_extended_cli() {
    phase "Phase 4.5 — extended CLI surface (init, generate, apply variants, clear)"

    local T="$DROPBOX_DIR/$TEST_SUBDIR"
    rm -rf "$T"; mkdir -p "$T"

    # 4g — dbxignore init scaffolds a starter .dropboxignore
    note "4g — dbxignore init"
    if dbxignore init "$T" >/dev/null 2>&1; then
        pass "4g — init (rc=0)"
    else
        fail "4g — init"
    fi
    if [ -f "$T/.dropboxignore" ] && grep -q 'Generated by .dbxignore init.' "$T/.dropboxignore"; then
        pass "4g — init wrote header"
    else
        fail "4g — init did not write expected header"
    fi

    # 4g — init refuses an unwritable target dir with exit 2 + a clean
    # "cannot write" message rather than an unhandled OSError traceback (PR #248).
    note "4g — dbxignore init on an unwritable directory"
    local ro_dir="$T/init-readonly"
    mkdir -p "$ro_dir"
    chmod 000 "$ro_dir"
    dbxignore init "$ro_dir" >/tmp/dbx-init-ro.out 2>&1 && rc=0 || rc=$?
    chmod 755 "$ro_dir"
    if [ "$rc" -eq 2 ]; then
        pass "4g — init exits 2 on an unwritable dir"
    else
        fail "4g — init exited $rc on an unwritable dir (expected 2)"
    fi
    assert_grep /tmp/dbx-init-ro.out 'cannot write' "4g — init stderr says 'cannot write'"

    # 4h — dbxignore generate translates a .gitignore byte-for-byte
    note "4h — dbxignore generate (byte-for-byte)"
    rm -rf "$T"; mkdir -p "$T"
    printf 'node_modules/\n*.log\n' > "$T/source.gitignore"
    if dbxignore generate "$T/source.gitignore" >/dev/null 2>&1; then
        pass "4h — generate (rc=0)"
    else
        fail "4h — generate"
    fi
    if [ -f "$T/.dropboxignore" ] && diff -q "$T/.dropboxignore" "$T/source.gitignore" >/dev/null 2>&1; then
        pass "4h — generate produced byte-for-byte copy"
    else
        fail "4h — generate output differs from source"
    fi

    # 4i — generate warns on dropped negation (PR #108)
    note "4i — generate emits stderr warning on dropped negation"
    rm -rf "$T"; mkdir -p "$T"
    printf 'build/\n!build/keep/\n' > "$T/source.gitignore"
    if dbxignore generate "$T/source.gitignore" --force 2>/tmp/dbx-gen-warn.err >/dev/null; then
        pass "4i — generate exits 0 even with conflict warning"
    else
        fail "4i — generate"
    fi
    assert_grep /tmp/dbx-gen-warn.err 'dropped negation' "4i — generate stderr says 'dropped negation'"
    assert_grep /tmp/dbx-gen-warn.err '!build/keep/'    "4i — generate stderr names the negation"
    # Byte-for-byte invariant survives the warning.
    if diff -q "$T/.dropboxignore" "$T/source.gitignore" >/dev/null 2>&1; then
        pass "4i — file content unchanged despite warning"
    else
        fail "4i — file content differs from source despite warning"
    fi

    # 4j — apply --dry-run does not mutate (PR #103)
    note "4j — apply --dry-run"
    rm -rf "$T"; mkdir -p "$T"
    printf '*.tmp\n' > "$T/.dropboxignore"
    : > "$T/foo.tmp"
    if dbxignore apply "$T" --dry-run >/tmp/dbx-dry.out 2>&1; then
        pass "4j — apply --dry-run (rc=0)"
    else
        fail "4j — apply --dry-run"
    fi
    assert_grep /tmp/dbx-dry.out 'would mark:'   "4j — dry-run lists 'would mark:' line"
    assert_grep /tmp/dbx-dry.out 'would_mark=1'  "4j — dry-run summary has would_mark=1"
    assert_xattr_unset "$T/foo.tmp" "4j — dry-run did not mutate marker"

    # 4k — apply --yes runs without prompting (PR #107)
    note "4k — apply --yes skips the prompt"
    if dbxignore apply "$T" --yes >/tmp/dbx-yes.out 2>&1; then
        pass "4k — apply --yes (rc=0)"
    else
        fail "4k — apply --yes"
    fi
    assert_xattr_set "$T/foo.tmp" "4k — apply --yes set marker"
    if ! grep -q 'Continue?' /tmp/dbx-yes.out; then
        pass "4k — --yes skipped the prompt"
    else
        note "$(cat /tmp/dbx-yes.out)"
        fail "4k — --yes did not skip the prompt"
    fi

    # 4l — apply on already-converged state says "Nothing to apply" (PR #107)
    note "4l — apply on no-op state"
    # No input piped: if a prompt fires, the command would block; we stub
    # stdin closed so any prompt would error out — passing means no prompt.
    if dbxignore apply "$T" </dev/null >/tmp/dbx-noop.out 2>&1; then
        pass "4l — apply on no-op state (rc=0)"
    else
        fail "4l — apply on no-op state"
    fi
    assert_grep /tmp/dbx-noop.out 'Nothing to apply' "4l — emits 'Nothing to apply (rules already in sync)'"

    # 4m — detector regression: case4m_target/* + !case4m_target/keep/ no conflict (PR #108)
    # Uses `case4m_target` instead of the generic `build` because testers who
    # have run `dbxignore init` at their Dropbox root carry a `build/` rule
    # at the ancestor `.dropboxignore`. Dropbox's directory-inheritance
    # semantic would then mark the test's `build/` via the ancestor rule and
    # mask the local `!build/keep/` negation — a real but unrelated effect
    # that the case 4m assertion would mis-attribute as "detector fix didn't
    # apply" (backlog item #111).
    note "4m — detector fix: case4m_target/* + !case4m_target/keep/ no conflict"
    rm -rf "$T"; mkdir -p "$T/case4m_target/keep"
    printf 'case4m_target/*\n!case4m_target/keep/\n' > "$T/.dropboxignore"
    : > "$T/case4m_target/keep/inside.txt"
    : > "$T/case4m_target/foo.tmp"
    if dbxignore apply "$T" --yes >/dev/null 2>&1; then
        pass "4m — apply (rc=0)"
    else
        fail "4m — apply"
    fi
    assert_xattr_set   "$T/case4m_target/foo.tmp" "4m — case4m_target/foo.tmp marked (case4m_target/* matches)"
    assert_xattr_unset "$T/case4m_target/keep"    "4m — case4m_target/keep NOT marked (negation now effective post-fix)"
    assert_xattr_unset "$T/case4m_target"         "4m — case4m_target/ NOT marked (children-only rule)"
    # status should report 0 conflicts for this rule set (the negation IS effective).
    local status_out; status_out="$(dbxignore status 2>&1)"
    if printf '%s\n' "$status_out" | grep -qE 'rule conflicts \([1-9]'; then
        note "$(printf '%s\n' "$status_out" | grep -A 5 'rule conflicts')"
        fail "4m — status reports >=1 conflicts (regression: detector fix didn't apply)"
    else
        pass "4m — status reports no conflicts (detector fix applied)"
    fi

    # 4n — dbxignore clear basic (PR #100); daemon-alive guard tested in phase 5
    note "4n — dbxignore clear (basic, daemon not alive)"
    if dbxignore clear "$T" --yes >/tmp/dbx-clear.out 2>&1; then
        pass "4n — clear (rc=0)"
    else
        fail "4n — clear"
        sed 's/^/    /' /tmp/dbx-clear.out
    fi
    assert_xattr_unset "$T/case4m_target/foo.tmp" "4n — clear removed case4m_target/foo.tmp marker"

    # 4o — dbxignore ignore <path> happy path (PR #191)
    note "4o — dbxignore ignore (basic)"
    local target_4o="$DROPBOX_DIR/dbxignore_test_4o"
    rm -rf "$target_4o"; mkdir -p "$target_4o"
    if dbxignore ignore "$target_4o" --yes >/tmp/dbx-ignore.out 2>&1; then
        pass "4o — ignore (rc=0)"
    else
        fail "4o — ignore"
        sed 's/^/    /' /tmp/dbx-ignore.out
    fi
    if grep -q 'dbxignore_test_4o/' "$DROPBOX_DIR/.dropboxignore" 2>/dev/null; then
        pass "4o — rule appended to $DROPBOX_DIR/.dropboxignore"
    else
        fail "4o — rule not appended to $DROPBOX_DIR/.dropboxignore"
    fi
    assert_xattr_set "$target_4o" "4o — marker set on target"

    # 4p — dbxignore unignore <path> happy path (PR #191)
    note "4p — dbxignore unignore (basic)"
    if dbxignore unignore "$target_4o" --yes >/tmp/dbx-unignore.out 2>&1; then
        pass "4p — unignore (rc=0)"
    else
        fail "4p — unignore"
        sed 's/^/    /' /tmp/dbx-unignore.out
    fi
    if grep -q 'dbxignore_test_4o/' "$DROPBOX_DIR/.dropboxignore" 2>/dev/null; then
        fail "4p — rule still present in $DROPBOX_DIR/.dropboxignore"
    else
        pass "4p — rule removed from $DROPBOX_DIR/.dropboxignore"
    fi
    assert_xattr_unset "$target_4o" "4p — marker cleared on target"
    rm -rf "$target_4o"

    # 4q — dbxignore unignore wildcard collision (PR #191)
    note "4q — dbxignore unignore refuses wildcard blocker"
    local target_4q="$DROPBOX_DIR/dbxignore_test_4q"
    rm -rf "$target_4q"; mkdir -p "$target_4q"
    printf 'dbxignore_test_4q/\n**/dbxignore_test_4q/\n' >> "$DROPBOX_DIR/.dropboxignore"
    if dbxignore unignore "$target_4q" --yes >/tmp/dbx-4q.out 2>&1; then
        fail "4q — unignore should have refused (wildcard blocker present)"
    else
        pass "4q — unignore refused with wildcard blocker"
    fi
    # Cleanup: remove the two test rules from .dropboxignore.
    { grep -v 'dbxignore_test_4q/' "$DROPBOX_DIR/.dropboxignore" || true; } > /tmp/dbx-4q-clean.tmp
    mv /tmp/dbx-4q-clean.tmp "$DROPBOX_DIR/.dropboxignore"
    # Clean up the root .dropboxignore if Phase 4.5 was its only contents.
    if [ -f "$DROPBOX_DIR/.dropboxignore" ] && \
       ! grep -v -E '^(#.*|\s*)$' "$DROPBOX_DIR/.dropboxignore" >/dev/null 2>&1; then
        rm -f "$DROPBOX_DIR/.dropboxignore"
    fi
    rm -rf "$target_4q"

    # 4r — clear/list exit 2 on nonexistent path (PR #195, item #95)
    note "4r — clear/list error on nonexistent path"
    local nonexist="$DROPBOX_DIR/dbxignore-test-nonexistent-$$"

    # clear on nonexistent path should exit 2
    if dbxignore clear "$nonexist" --yes >/tmp/dbx-4r-clear.err 2>&1; then
        fail "4r — clear should exit 2 on nonexistent path"
    else
        local exit_code=$?
        if [ $exit_code -eq 2 ]; then
            pass "4r — clear exits 2 on nonexistent path"
        else
            fail "4r — clear exited $exit_code instead of 2"
        fi
    fi
    assert_grep /tmp/dbx-4r-clear.err 'does not exist' "4r — clear stderr says 'does not exist'"

    # list on nonexistent path should exit 2
    if dbxignore list "$nonexist" >/tmp/dbx-4r-list.err 2>&1; then
        fail "4r — list should exit 2 on nonexistent path"
    else
        local exit_code=$?
        if [ $exit_code -eq 2 ]; then
            pass "4r — list exits 2 on nonexistent path"
        else
            fail "4r — list exited $exit_code instead of 2"
        fi
    fi
    assert_grep /tmp/dbx-4r-list.err 'does not exist' "4r — list stderr says 'does not exist'"

    # 4s — clear fail-closed on unreadable state.json (PR #203, item #97 Codex P2 followup)
    # state.json exists but `state.read()` returns None (chmod 000 → PermissionError
    # → _read_at returns None). cli.clear refuses to proceed because daemon liveness
    # is unknown; --force overrides.
    #
    # Recovery: sentinels (`_4S_STATE_JSON`, `_4S_STATE_JSON_EXISTED`) are set
    # BEFORE the destructive overwrite. The parent script's EXIT trap calls
    # `_phase_4s_recover_state_json` to chmod 644 + restore content if a `set -e`
    # abort fires anywhere between the overwrite and the explicit restore at the
    # end. Sentinels are unset after the successful restore, making the recovery
    # hook a no-op.
    note "4s — clear fail-closed on unreadable state.json"
    mkdir -p "$DBXIGNORE_STATE_DIR"
    local state_json="$DBXIGNORE_STATE_DIR/state.json"
    local state_json_existed=0
    if [ -f "$state_json" ]; then
        state_json_existed=1
        cp -p "$state_json" /tmp/dbx-4s-state-backup.json
    fi

    # Install recovery sentinels BEFORE the first destructive operation.
    # The parent cleanup() trap reads these; unset on successful completion.
    _4S_STATE_JSON="$state_json"
    _4S_STATE_JSON_EXISTED="$state_json_existed"

    printf '{}\n' > "$state_json"

    # Setup the test target. Any setup failure aborts cleanly via the parent's
    # EXIT trap, which calls _phase_4s_recover_state_json to restore state.json.
    rm -rf "$T"; mkdir -p "$T"
    printf '*.tmp\n' > "$T/.dropboxignore"
    : > "$T/foo.tmp"
    dbxignore apply "$T" --yes >/dev/null 2>&1

    # Lock window 1: just the dbxignore clear call (no setup, no assertions inside).
    local clear_rc
    chmod 000 "$state_json"
    if dbxignore clear "$T" --yes >/tmp/dbx-4s-clear.out 2>/tmp/dbx-4s-clear.err; then
        clear_rc=0
    else
        clear_rc=$?
    fi
    chmod 644 "$state_json"

    if [ "$clear_rc" -eq 2 ]; then
        pass "4s — clear exits 2 on unreadable state.json"
    else
        fail "4s — clear exited $clear_rc instead of 2"
    fi
    assert_grep /tmp/dbx-4s-clear.err 'unreadable' "4s — clear stderr names 'unreadable' state file"
    # Marker still set — fail-closed means no destructive action ran.
    assert_xattr_set "$T/foo.tmp" "4s — clear did not clear marker (refused)"

    # Lock window 2: --force test.
    local force_rc
    chmod 000 "$state_json"
    if dbxignore clear "$T" --yes --force >/tmp/dbx-4s-force.out 2>&1; then
        force_rc=0
    else
        force_rc=$?
    fi
    chmod 644 "$state_json"

    if [ "$force_rc" -eq 0 ]; then
        pass "4s — clear --force overrides the unreadable-state guard"
    else
        fail "4s — clear --force should succeed (exit=$force_rc)"
    fi
    assert_xattr_unset "$T/foo.tmp" "4s — clear --force cleared the marker"

    # Restore state.json content and unset the recovery sentinels.
    if [ "$state_json_existed" -eq 1 ]; then
        mv /tmp/dbx-4s-state-backup.json "$state_json"
    else
        rm -f "$state_json"
    fi
    unset _4S_STATE_JSON _4S_STATE_JSON_EXISTED

    # 4t — path-taking verbs refuse `..` after a symlinked component (PR #205, item #105)
    # Lexical normalization of `link/..` differs from filesystem-true resolution;
    # `_normalize_under_root` rejects the path up-front. Test one verb (explain)
    # — the guard is in the shared validator and unit tests cover all 5 verbs.
    note "4t — explain refuses '..-after-symlink' path"
    rm -rf "$T"; mkdir -p "$T"
    local link_target="$T/target-dir"
    mkdir -p "$link_target"
    : > "$link_target/file.txt"
    ln -s "$link_target" "$T/link"

    local link_dotdot_arg="$T/link/../file.txt"
    if dbxignore explain "$link_dotdot_arg" >/tmp/dbx-4t-explain.out 2>/tmp/dbx-4t-explain.err; then
        fail "4t — explain should refuse '..-after-symlink' path"
    else
        local exit_code=$?
        if [ $exit_code -eq 2 ]; then
            pass "4t — explain exits 2 on '..-after-symlink' path"
        else
            fail "4t — explain exited $exit_code instead of 2"
        fi
    fi
    assert_grep /tmp/dbx-4t-explain.err 'symlinked component' \
        "4t — explain stderr names 'symlinked component'"
}
