# Sourced by scripts/manual-test-{ubuntu-vps,macos}.sh.
#
# Defines `phase_extended_cli()`, the Phase 4.5 block exercising the CLI
# surface added across PRs #100, #102, #103, #107, #108. Extracted because
# the body is byte-near-identical between the two scripts (~120 LOC each)
# and was being maintained twice; backlog item #75 is the trigger.
#
# Depends on the parent script's shared environment:
#   - $DROPBOX_DIR, $TEST_SUBDIR — test-tree location
#   - phase, note, pass, fail — output helpers
#   - assert_grep, assert_xattr_set, assert_xattr_unset — assertion helpers
#
# Windows (`scripts/manual-test-windows.ps1`) is PowerShell and does not
# share this body — see backlog item #75.

phase_extended_cli() {
    phase "Phase 4.5 — extended CLI surface (init, generate, apply variants, clear)"

    local T="$DROPBOX_DIR/$TEST_SUBDIR"
    rm -rf "$T"; mkdir -p "$T"

    # 4g — dbxignore init scaffolds a starter .dropboxignore
    note "4g — dbxignore init"
    if dbxignore init "$T" >/dev/null 2>&1; then
        pass "4g — init (rc=0)"
    else
        fail "4g — init"
    fi
    if [ -f "$T/.dropboxignore" ] && grep -q 'Generated by .dbxignore init.' "$T/.dropboxignore"; then
        pass "4g — init wrote header"
    else
        fail "4g — init did not write expected header"
    fi

    # 4h — dbxignore generate translates a .gitignore byte-for-byte
    note "4h — dbxignore generate (byte-for-byte)"
    rm -rf "$T"; mkdir -p "$T"
    printf 'node_modules/\n*.log\n' > "$T/source.gitignore"
    if dbxignore generate "$T/source.gitignore" >/dev/null 2>&1; then
        pass "4h — generate (rc=0)"
    else
        fail "4h — generate"
    fi
    if [ -f "$T/.dropboxignore" ] && diff -q "$T/.dropboxignore" "$T/source.gitignore" >/dev/null 2>&1; then
        pass "4h — generate produced byte-for-byte copy"
    else
        fail "4h — generate output differs from source"
    fi

    # 4i — generate warns on dropped negation (PR #108)
    note "4i — generate emits stderr warning on dropped negation"
    rm -rf "$T"; mkdir -p "$T"
    printf 'build/\n!build/keep/\n' > "$T/source.gitignore"
    if dbxignore generate "$T/source.gitignore" --force 2>/tmp/dbx-gen-warn.err >/dev/null; then
        pass "4i — generate exits 0 even with conflict warning"
    else
        fail "4i — generate"
    fi
    assert_grep /tmp/dbx-gen-warn.err 'dropped negation' "4i — generate stderr says 'dropped negation'"
    assert_grep /tmp/dbx-gen-warn.err '!build/keep/'    "4i — generate stderr names the negation"
    # Byte-for-byte invariant survives the warning.
    if diff -q "$T/.dropboxignore" "$T/source.gitignore" >/dev/null 2>&1; then
        pass "4i — file content unchanged despite warning"
    else
        fail "4i — file content differs from source despite warning"
    fi

    # 4j — apply --dry-run does not mutate (PR #103)
    note "4j — apply --dry-run"
    rm -rf "$T"; mkdir -p "$T"
    printf '*.tmp\n' > "$T/.dropboxignore"
    : > "$T/foo.tmp"
    if dbxignore apply "$T" --dry-run >/tmp/dbx-dry.out 2>&1; then
        pass "4j — apply --dry-run (rc=0)"
    else
        fail "4j — apply --dry-run"
    fi
    assert_grep /tmp/dbx-dry.out 'would mark:'   "4j — dry-run lists 'would mark:' line"
    assert_grep /tmp/dbx-dry.out 'would_mark=1'  "4j — dry-run summary has would_mark=1"
    assert_xattr_unset "$T/foo.tmp" "4j — dry-run did not mutate marker"

    # 4k — apply --yes runs without prompting (PR #107)
    note "4k — apply --yes skips the prompt"
    if dbxignore apply "$T" --yes >/tmp/dbx-yes.out 2>&1; then
        pass "4k — apply --yes (rc=0)"
    else
        fail "4k — apply --yes"
    fi
    assert_xattr_set "$T/foo.tmp" "4k — apply --yes set marker"
    if ! grep -q 'Continue?' /tmp/dbx-yes.out; then
        pass "4k — --yes skipped the prompt"
    else
        note "$(cat /tmp/dbx-yes.out)"
        fail "4k — --yes did not skip the prompt"
    fi

    # 4l — apply on already-converged state says "Nothing to apply" (PR #107)
    note "4l — apply on no-op state"
    # No input piped: if a prompt fires, the command would block; we stub
    # stdin closed so any prompt would error out — passing means no prompt.
    if dbxignore apply "$T" </dev/null >/tmp/dbx-noop.out 2>&1; then
        pass "4l — apply on no-op state (rc=0)"
    else
        fail "4l — apply on no-op state"
    fi
    assert_grep /tmp/dbx-noop.out 'Nothing to apply' "4l — emits 'Nothing to apply (rules already in sync)'"

    # 4m — detector regression: build/* + !build/keep/ no conflict (PR #108)
    note "4m — detector fix: build/* + !build/keep/ no conflict"
    rm -rf "$T"; mkdir -p "$T/build/keep"
    printf 'build/*\n!build/keep/\n' > "$T/.dropboxignore"
    : > "$T/build/keep/inside.txt"
    : > "$T/build/foo.tmp"
    if dbxignore apply "$T" --yes >/dev/null 2>&1; then
        pass "4m — apply (rc=0)"
    else
        fail "4m — apply"
    fi
    assert_xattr_set   "$T/build/foo.tmp" "4m — build/foo.tmp marked (build/* matches)"
    assert_xattr_unset "$T/build/keep"    "4m — build/keep NOT marked (negation now effective post-fix)"
    assert_xattr_unset "$T/build"         "4m — build/ NOT marked (children-only rule)"
    # status should report 0 conflicts for this rule set (the negation IS effective).
    local status_out; status_out="$(dbxignore status 2>&1)"
    if printf '%s\n' "$status_out" | grep -qE 'rule conflicts \([1-9]'; then
        note "$(printf '%s\n' "$status_out" | grep -A 5 'rule conflicts')"
        fail "4m — status reports >=1 conflicts (regression: detector fix didn't apply)"
    else
        pass "4m — status reports no conflicts (detector fix applied)"
    fi

    # 4n — dbxignore clear basic (PR #100); daemon-alive guard tested in phase 5
    note "4n — dbxignore clear (basic, daemon not alive)"
    if dbxignore clear "$T" --yes >/tmp/dbx-clear.out 2>&1; then
        pass "4n — clear (rc=0)"
    else
        fail "4n — clear"
        sed 's/^/    /' /tmp/dbx-clear.out
    fi
    assert_xattr_unset "$T/build/foo.tmp" "4n — clear removed build/foo.tmp marker"
}
